exclude_patterns:
  - "**/node_modules/"
  - "**/*.d.ts"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.snap"

plugins:
  fixme:
    enabled: true
  shellcheck:
    enabled: true
  # Disabled due to https://github.com/tkqubo/codeclimate-tslint/issues/46
  # tslint:
  #   enabled: true
  #   config: tslint.json
