language: node_js

node_js:
  - 10.10.0

cache:
  yarn: true
  directories:
    - ~/.npm
    - ~/.cache

jobs:
  include:
    - stage: test
      name: "Unit tests"
      script: ./scripts/unit-tests.sh
    - script: ./scripts/e2e-tests.sh
      name: "End to end tests"
    - script: ./scripts/build-game.sh
      name: "Build game"

stages:
  - test
  - name: deploy
    if: branch = master
    provider: firebase
    skip_cleanup: true

notifications:
  email:
    on_failure: change
    on_success: never
