language: node_js

node_js:
  - 10.10.0

cache:
  yarn: true
  directories:
    - ~/.npm
    - ~/.cache

jobs:
  include:
    - stage: test
      name: "Unit tests"
      script: ./scripts/run-unit-tests.sh
    - script: yarn test:ci
      name: "End to end tests"
    - script: yarn build
      name: "Build app"

stages:
  - test
  - name: deploy
    if: branch = master
    provider: firebase
    skip_cleanup: true

notifications:
  email:
    on_failure: change
    on_success: never
